### ISSUE TITLE
After installing the plugin does not have a file index.js

### ISSUE THREAD

**Issue by mrmlnc** [nodaguti/gulp-electron-mocha#13]
#### Package.json
```json
{
    "main": "./lib/index.js",
}
```

#### Directory
![image](https://cloud.githubusercontent.com/assets/7034281/16337741/5e2af3d2-3a20-11e6-9047-216e7d3bbcf2.png)

#### Error
```shell
module.js:442
    throw err;
    ^

Error: Cannot find module 'gulp-electron-mocha'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at taskDeps.forEach (C:\projects\yellfy\gulp\yellfy\use.js:46:38)
    at Array.forEach (native)
    at global.use (C:\projects\yellfy\gulp\yellfy\use.js:44:12)
    at Object.<anonymous> (C:\projects\yellfy\gulp\tasks\test.js:3:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

**Comment by ngprasad** [comment]
Same problem. Please fix it soon otherwise we won't be able to use this package.

**Comment by nodaguti** [comment]
Thank you for reporting and I'm really sorry for taking it long to fix it.
I have no idea why suddenly lib/ was excluded from a published package, but I believe everything is fine now.
Thank you for your patience!
