### ISSUE TITLE
Cannot find module 'babel-runtime/helpers/toConsumableArray'

### ISSUE THREAD

**Issue by JoshuaBStevens** [nodaguti/gulp-electron-mocha#2]
This is probably user error, but I'm a newbie so maybe someone can help.  I installed electron, electron-mocha, and gulp-electron-mocha.  But when I try to invoke gulp-electron-mocha from gulpfile.js (with no parameters), I get this error:

module.js:328
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/toConsumableArray'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\git\xShellSamples\SettingsViewer\App\node_modules\gulp-electron-mocha\lib\index.js:45:27)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by benedictchen** [comment]
`npm install babel-core`
