### ISSUE TITLE
electronMocha is not a function

### ISSUE THREAD

**Issue by ngprasad** [nodaguti/gulp-electron-mocha#4]
Here's my gulpfile.js:-

'use strict';

var gulp = require('gulp');
var electronMocha = require('gulp-electron-mocha');
/*
Execute all tests.
*/
gulp.task('run-tests', function () {
    return gulp.src('./test', { read: false })
               .pipe(electronMocha());
});

It's giving me the following error when I run on vscode.

TypeError: electronMocha is not a function
    at Gulp.<anonymous> (/Users/nischalp/dev/mamba_workspace/qbo-client/gulpfile.js:11:22)
    at module.exports (/Users/nischalp/dev/mamba_workspace/qbo-client/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/nischalp/dev/mamba_workspace/qbo-client/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/nischalp/dev/mamba_workspace/qbo-client/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/nischalp/dev/mamba_workspace/qbo-client/node_modules/orchestrator/index.js:134:8)
    at /Users/nischalp/.nvm/versions/node/v5.9.0/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (node.js:376:9)
    at process._tickCallback (node.js:407:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:142:18)

Any help will be appreciated.

Thanks,

**Comment by ngprasad** [comment]
Any updates on this? I opened this 4 days back.

**Comment by aaronbski** [comment]
Try:
`var electronMocha = require('gulp-electron-mocha').default;`

**Comment by ngprasad** [comment]
Yes that works! Thanks!
