### ISSUE TITLE
error in plugin gulp-electron-mocha

### ISSUE THREAD

**Issue by ngprasad** [nodaguti/gulp-electron-mocha#5]
Getting the following error:-

Can someone pls help me out here

(node:98250) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:42:38] Using gulpfile ~/dev/mamba_workspace/qbo-client/gulpfile.js
[23:42:38] Starting 'test'...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn dist/Electron.app/Contents/MacOS/Electron ENOENT
    at exports._errnoException (util.js:896:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[23:42:38] 'test' errored after 96 ms
[23:42:38] Error in plugin 'gulp-electron-mocha'
Message:
    Test failed. electronMocha exit code: 1

**Comment by ngprasad** [comment]
I was able to resolve this. The instructions here are not correct. Under Install "Note that you don't have to install either electron-mocha or electron-prebuilt globally (i.e. with npm i -g). All dependencies are resolved automatically."

Actually you need to have electron-prebuilt installed globally in order for gulp-electron-mocha to work.
